#!/usr/bin/env python3
"""
The two evaluation contracts, generated from contracts/keepalive.py.

    python scripts/gen_probe.py           # write eval/probe_contract.py and eval/web_probe.py
    python scripts/gen_probe.py --check   # exit 1 unless both are exactly what this writes

A copy that is "the same rubric and fetch code" by intention drifts; one that
is generated cannot. Every shared function and constant is lifted out of the
contract's parsed source verbatim, and tests/test_static.py compares the parsed
trees function by function as well, so a hand edit to either file fails twice.

    eval/probe_contract.py  the judge with no money: the golden cases run
                            through it, with past windows, which a real stream
                            can never have
    eval/web_probe.py       throwaway: what each kind of page looks like to
                            validators through the exact fetch the judge uses
"""

from __future__ import annotations

import ast
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
CONTRACT = ROOT / "contracts" / "keepalive.py"
PROBE = ROOT / "eval" / "probe_contract.py"
WEB_PROBE = ROOT / "eval" / "web_probe.py"
RUBRIC = ROOT / "web" / "lib" / "rubric.json"

#: What the judge is made of. Order matters only for readability; every name
#: is defined before it is used at import time.
JUDGE_NAMES = (
    "E", "X", "T", "L",
    "ALIVE", "QUIET", "OFF_MISSION", "UNREADABLE", "VERDICTS",
    "MAX_MISSION", "MAX_SUMMARY", "MAX_LINK", "MAX_EVIDENCE", "PAGE_CHARS", "MAX_REASON",
    "GITHUB_API", "_EPOCH", "CHECK", "EVIDENCE_LINE", "NOT_READ",
    "_seconds", "_iso",
    "fence", "commits_digest", "fetch", "build_prompt", "parse_verdict", "ask", "judge",
    "run_judgment", "error_text", "same_error",
)

FETCH_NAMES = ("E", "PAGE_CHARS", "GITHUB_API", "NOT_READ", "commits_digest", "fetch")

HEADER = '''# { "Depends": "py-genlayer:1jb45aa8ynh2a9c9xn3b7qqh8sm5q93hwfp7jqmwsfhh8jpz09h6" }'''

IMPORTS = '''import datetime
import hashlib
import json
import re

from genlayer import *'''

PROBE_DOC = '''"""
KeepaliveProbe - the Keepalive judge with no money.

GENERATED by scripts/gen_probe.py from contracts/keepalive.py. Do not edit:
every function above the class is the contract's own, lifted verbatim, and
tests/test_static.py fails if the two ever differ.

Why it exists. A real stream always starts when it is opened, so a stream can
never be pointed at last month to test the judge. This contract has one write
method, probe(), with the same rubric, the same fetch code and the same
consensus block as check(), no money, and past windows allowed, which lets the
golden cases use windows whose ground truth is already known.
"""'''

PROBE_CLASS = '''

MAX_CASE_ID = 24


class KeepaliveProbe(gl.Contract):
    owner: Address
    count: u64
    #: case id -> the stored result, as JSON
    results: TreeMap[str, str]
    #: run number -> case id, in the order the cases ran
    order: TreeMap[str, str]

    def __init__(self):
        self.owner = gl.message.sender_address
        self.count = u64(0)

    @gl.public.write
    def probe(self, case_id: str, mission: str, start: str, end: str, report: str, links: list[str]) -> None:
        """
        One golden case through the judge.

        The owner only: every call spends the validators' model budget, and an
        open probe would let anybody fill the results with rows the evaluation
        never ran. A stored case id is never overwritten, so a result is
        reported as it came out; a deliberate second run takes a new id.
        The window must be closed, exactly as check() requires.
        """
        if gl.message.sender_address != self.owner:
            raise gl.vm.UserError(E + "only the owner may probe")
        cid = case_id.strip()
        if cid == "" or len(cid) > MAX_CASE_ID:
            raise gl.vm.UserError(E + "case id must be 1 to 24 characters")
        if cid in self.results:
            raise gl.vm.UserError(E + "case already run")
        start_s = _seconds(start)
        end_s = _seconds(end)
        now = _seconds(gl.message_raw["datetime"])
        if end_s <= start_s:
            raise gl.vm.UserError(E + "window ends before it starts")
        if end_s > now:
            raise gl.vm.UserError(E + "window must be closed")
        text = " ".join(mission.split())
        if text == "" or len(text) > MAX_MISSION:
            raise gl.vm.UserError(E + "mission must be 1 to 400 characters")
        summary = report.strip()
        if summary == "" or len(summary) > MAX_SUMMARY:
            raise gl.vm.UserError(E + "report must be 1 to 800 characters")
        if len(links) > MAX_EVIDENCE:
            raise gl.vm.UserError(E + "up to four links")
        urls: list[str] = []
        for raw in links:
            link = str(raw).strip()
            if not link.startswith("https://") or len(link) > MAX_LINK:
                raise gl.vm.UserError(E + "links must be https and at most 300 characters")
            urls.append(link)

        out = run_judgment(text, _iso(start_s), _iso(end_s), _iso(now), summary, urls)

        row = {
            "case_id": cid,
            "verdict": out["verdict"],
            "reason": out["reason"],
            "pages": int(out["pages"]),
            "readable": int(out["readable"]),
            "start": _iso(start_s),
            "end": _iso(end_s),
            "checked_at": _iso(now),
            "links": urls,
            "prober": gl.message.sender_address.as_hex,
        }
        self.results[cid] = json.dumps(row, sort_keys=True)
        self.count = u64(int(self.count) + 1)
        self.order[str(int(self.count))] = cid

    @gl.public.view
    def get_result(self, case_id: str) -> str:
        if case_id not in self.results:
            raise gl.vm.UserError(E + "no such case")
        return self.results[case_id]

    @gl.public.view
    def list_results(self) -> str:
        rows = []
        for n in range(1, int(self.count) + 1):
            rows.append(json.loads(self.results[self.order[str(n)]]))
        return json.dumps(rows, sort_keys=True)
'''

WEB_DOC = '''"""
WebProbe - throwaway: what each kind of evidence page looks like to validators.

GENERATED by scripts/gen_probe.py from contracts/keepalive.py. Do not edit:
fetch() and commits_digest() above the class are the contract's own, lifted
verbatim, so mode "fetch" is exactly what the judge reads.

The leader's text crosses consensus and is stored: its length, a sha256 of it,
and the first 1,500 characters. Each validator fetches the same URL itself and
agrees only when its own page lands in the same readability class as the
leader's (at least 200 characters, and not an unreadable marker). A URL whose
readability differs between nodes therefore fails consensus, which is the
finding. Validators' own text never crosses, so running a URL more than once,
under rotating leaders, is how variation between nodes is seen.
"""'''

WEB_CLASS = '''

MODES = ("fetch", "render", "get")
EXCERPT = 1500
#: Absolute dates as pages print them: 2024-12-19, Dec 19, 2024, 19 Dec 2024.
DATE = re.compile(
    r"\\b(?:\\d{4}-\\d{2}-\\d{2}|(?:Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec)[a-z]* \\d{1,2},? \\d{4}"
    r"|\\d{1,2} (?:Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec)[a-z]* \\d{4})\\b"
)


def readable(text: str) -> str:
    """The class validators must agree on, as a token rather than a bool."""
    body = text.strip()
    if len(body) < 200 or body.startswith("[unreadable"):
        return "no"
    return "yes"


def read_page(url: str, mode: str) -> dict:
    """One fetch, as a flat dict of strings."""
    error = ""
    text = ""
    try:
        if mode == "fetch":
            text = fetch(url)
        elif mode == "render":
            text = str(gl.nondet.web.render(url, mode="text"))
        else:
            response = gl.nondet.web.get(url)
            body = b"" if response.body is None else response.body
            text = "HTTP " + str(response.status) + "\\n" + body.decode("utf-8", "replace")
    except Exception as failure:  # noqa: BLE001  the failure is the measurement
        error = (type(failure).__name__ + ": " + str(failure))[:300]
    return {
        "excerpt": text[:EXCERPT],
        "length": str(len(text)),
        "sha256": hashlib.sha256(text.encode("utf-8")).hexdigest(),
        "readable": readable(text),
        "error": error,
        "dates_in_cut": "|".join(DATE.findall(text[:PAGE_CHARS])[:8]),
    }


class WebProbe(gl.Contract):
    owner: Address
    count: u64
    rows: TreeMap[str, str]

    def __init__(self):
        self.owner = gl.message.sender_address
        self.count = u64(0)

    @gl.public.write
    def probe(self, label: str, url: str, mode: str) -> None:
        if gl.message.sender_address != self.owner:
            raise gl.vm.UserError(E + "only the owner may probe")
        if mode not in MODES:
            raise gl.vm.UserError(E + "mode is fetch, render or get")
        if not url.startswith("https://") or len(url) > 300:
            raise gl.vm.UserError(E + "url must be https and at most 300 characters")
        name = label.strip()[:60]
        target = url
        how = mode

        def leader_fn():
            return read_page(target, how)

        def validator_fn(leader_result) -> bool:
            if not isinstance(leader_result, gl.vm.Return):
                return False
            theirs = leader_result.calldata
            if not isinstance(theirs, dict):
                return False
            return read_page(target, how)["readable"] == theirs.get("readable")

        out = gl.vm.run_nondet_unsafe(leader_fn, validator_fn)
        self.count = u64(int(self.count) + 1)
        row = {
            "n": int(self.count),
            "label": name,
            "url": url,
            "mode": mode,
            "at": gl.message_raw["datetime"],
            "length": int(out["length"]),
            "sha256": out["sha256"],
            "readable": out["readable"],
            "error": out["error"],
            "dates_in_cut": out["dates_in_cut"],
            "excerpt": out["excerpt"],
        }
        self.rows[str(int(self.count))] = json.dumps(row, sort_keys=True)

    @gl.public.view
    def list_rows(self) -> str:
        return json.dumps([json.loads(self.rows[str(n)]) for n in range(1, int(self.count) + 1)], sort_keys=True)
'''


def lift(source: str, names: tuple[str, ...]) -> str:
    """The top level definitions named, verbatim, in the order given."""
    tree = ast.parse(source)
    lines = source.splitlines()
    found: dict[str, str] = {}
    for node in tree.body:
        if isinstance(node, (ast.FunctionDef, ast.ClassDef)):
            name = node.name
        elif isinstance(node, ast.Assign) and len(node.targets) == 1 and isinstance(node.targets[0], ast.Name):
            name = node.targets[0].id
        elif isinstance(node, ast.AnnAssign) and isinstance(node.target, ast.Name):
            name = node.target.id
        else:
            continue
        if name in names:
            start = min([node.lineno] + [d.lineno for d in getattr(node, "decorator_list", [])])
            found[name] = "\n".join(lines[start - 1 : node.end_lineno])
    missing = [name for name in names if name not in found]
    if missing:
        raise SystemExit(f"contracts/keepalive.py no longer defines {missing}")
    blocks = []
    for name in names:
        block = found[name]
        blocks.append(block + ("\n" if block.startswith(("def ", "class ", "@")) else ""))
    return "\n\n".join(blocks).rstrip() + "\n"


def render() -> dict[pathlib.Path, str]:
    source = CONTRACT.read_text(encoding="utf-8")
    probe = "\n".join([HEADER, PROBE_DOC, "", IMPORTS, "", "", lift(source, JUDGE_NAMES)]) + PROBE_CLASS
    web = "\n".join([HEADER, WEB_DOC, "", IMPORTS, "", "", lift(source, FETCH_NAMES)]) + WEB_CLASS
    return {PROBE: probe, WEB_PROBE: web, RUBRIC: rubric(source)}


def rubric(source: str) -> str:
    """The rubric for the site's /rubric page: the contract's own constant, never a retyped copy."""
    import hashlib
    import json

    values = {}
    for node in ast.parse(source).body:
        if isinstance(node, ast.Assign) and ast.unparse(node.targets[0]) in ("CHECK", "EVIDENCE_LINE", "PAGE_CHARS"):
            values[ast.unparse(node.targets[0])] = ast.literal_eval(node.value)
    record = {
        "check": values["CHECK"],
        "evidenceLine": values["EVIDENCE_LINE"],
        "pageChars": values["PAGE_CHARS"],
        "sha256": hashlib.sha256(values["CHECK"].encode("utf-8")).hexdigest(),
        "generatedBy": "scripts/gen_probe.py from contracts/keepalive.py",
    }
    return json.dumps(record, indent=2, sort_keys=True) + "\n"


def main() -> int:
    outputs = render()
    if "--check" in sys.argv:
        stale = [path for path, text in outputs.items() if not path.exists() or path.read_text(encoding="utf-8") != text]
        for path in stale:
            print(f"{path.relative_to(ROOT).as_posix()} is not what scripts/gen_probe.py writes. Run it.")
        return 1 if stale else 0
    for path, text in outputs.items():
        path.write_text(text, encoding="utf-8", newline="\n")
        print(f"wrote {path.relative_to(ROOT).as_posix()} ({len(text)} bytes)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
